---
- name: Check if net.ifnames=0 biosdevname=0 in grub file
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=".*net.ifnames=0 biosdevname=0'
    state: absent
  check_mode: true
  register: grub_file_check
  changed_when: false

- name: Add net.ifnames=0 biosdevname=0 to grub config
  become: true
  ansible.builtin.lineinfile:
    backup: true
    backrefs: true
    path: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX=.*)\"'
    line: '\1 net.ifnames=0 biosdevname=0"'
  when: grub_file_check.found == 0
  notify: 
  - Update grub